S T U B

diff --git a/src/init/init b/src/init/init
--- a/src/init/init
+++ b/src/init/init
@@ -1,28 +1,27 @@
-#!/bedrock/libexec/busybox sh
-#
-# init
-#
-#      This program is free software; you can redistribute it and/or
-#      modify it under the terms of the GNU General Public License
-#      version 2 as published by the Free Software Foundation.
-#
-# Copyright (c) 2014-2018 Daniel Thau <danthau@bedrocklinux.org>
-#
+#!/bin/sh
+# Copyright 2019 Jacob Hrbek <kreyren@rixotstudio.cz>
+# Distributed under the terms of the GNU General Public License v3 (https://www.gnu.org/licenses/gpl-3.0.en.html) or later
+# Based in part upon 'init' from Bedrock Linux (https://github.com/bedrocklinux/bedrocklinux-userland/blob/master/src/init/init), which is:
+# 		Copyright 2016-2019 Daniel Thau <danthau@bedrocklinux.org> as GPLv2
+
 # Bedrock Linux meta-init system
 
-. /bedrock/share/common-code
+# shellcheck source=src/slash-bedrock/lib/shell/common-code.sh
+. /bedrock/lib/shell/common-code.sh
+
 # Remove typical runtime sanity checks, as crashing during init is going to
 # just cause difficult to debug headaches for most users.
 set +eu
 trap '' EXIT
 
 fatal_error() {
-	echo ""
-	printf "${color_alert}${*}${color_norm}\\n"
-	echo ""
-	echo "Starting emergency shell"
-	echo "Good luck"
-	echo ""
+	printf '%s\n' \
+		'' \
+		"$color_alert$*$color_norm" \
+		'' \
+		"Starting emergency shell" \
+		"Good luck" \
+		''
 	exec sh
 }
 
@@ -100,13 +99,13 @@ ensure_essential_environment() {
 
 complete_hijack() {
 	step_init "6"
-	notice "Completing ${color_term}hijack install${color_norm}"
+	einfo "Completing ${color_term}hijack install${color_norm}"
 	hijacked="$(deref hijacked)"
 
 	step "Moving ${color_strat}${hijacked}${color_norm} files to ${color_file}/bedrock/strata/${hijacked}${color_norm}"
 	mkdir -p "/bedrock/strata/${hijacked}"
 	set_attr "/bedrock/strata/${hijacked}" "stratum" "${hijacked}"
-	cd /
+	cd / || die 1 "Function complete_hijack is unable to change directory in '/'"
 	for item in *; do
 		case "${item}" in
 		"proc" | "sys" | "dev" | "run" | "boot" | bedrock*)
@@ -194,11 +193,11 @@ wait_for_keyboard() {
 		usleep 250000 # quarter second
 	done
 
-	printf "\r"
+	printf '\r'
 	printf "Waiting up to %s seconds for keyboard initialization..." "${init_timeout}" | sed 's/./ /g'
-	printf "\r"
+	printf '\r'
 	if ! /bedrock/libexec/keyboard_is_present; then
-		notice "${color_warn}WARNING: unable to detect keyboard${color_norm}"
+		einfo "${color_warn}WARNING: unable to detect keyboard${color_norm}"
 	fi
 }
 
@@ -280,7 +279,9 @@ get_init_choice() {
 		if [ "${init_timeout}" -eq 0 ] && [ -n "${def_path}" ] && [ -x "${def_path}" ]; then
 			selected_num=0
 		elif [ "${init_timeout}" -gt 0 ] && [ -n "${def_path}" ] && [ -x "${def_path}" ]; then
-			printf "(${color_sub}${init_timeout}s${color_norm}): " >&2
+			printf '%s\n' "(${color_sub}${init_timeout}s${color_norm}): " >&2
+			fixme "read -t is undefined on POSIX, but defined in busybox(?), make it POSIX compatible"
+			# shellcheck disable=SC2039
 			read -r -t "${init_timeout}" selected_num
 		else
 			read -r selected_num
@@ -299,7 +300,7 @@ get_init_choice() {
 			list_init_options | awk -v"n=${selected_num}" 'NR==n {print $1":"$3}'
 			return
 		fi
-		printf "${color_alert}Unrecognized choice, try again.${color_norm}\\n" >&2
+		printf '%s\n' "${color_alert}Unrecognized choice, try again.${color_norm}" >&2
 	done
 }
 
@@ -311,9 +312,10 @@ pivot() {
 	mount --bind "/bedrock" "/bedrock/strata/${init_stratum}/bedrock"
 
 	# Pivot
-	cd "/bedrock/strata/${init_stratum}"
+	fixme "Attempt to avoid using cd in pivot function"
+	cd "/bedrock/strata/$init_stratum" || die 1 "Unable to change directory in '/bedrock/strata/$init_stratum'"
 	pivot_root "." "bedrock/strata/${init_stratum}"
-	cd /
+	cd / || die 1 "Function 'pivot' is unable to change directory in '/'"
 	mount --move "/bedrock/strata/${init_stratum}" "/bedrock/strata/bedrock"
 	# `man 8 pivot_root` says to `chroot .` here, but in practice this was
 	# found to make mount points inaccessible, and no problems were found when
@@ -378,7 +380,7 @@ if [ -n "${def_tuple}" ] && [ -d "/bedrock/strata/${def_stratum}" ]; then
 	umount "${sproc}"
 fi
 if [ -n "${def_tuple}" ] && [ -z "${def_path:-}" ]; then
-	notice "${color_warn}WARNING: ${color_file}/bedrock/etc/bedrock.conf [init]/default ${color_warn}value does not describe a valid stratum:init pair.${color_norm}"
+	einfo "${color_warn}WARNING: ${color_file}/bedrock/etc/bedrock.conf [init]/default ${color_warn}value does not describe a valid stratum:init pair.${color_norm}"
 fi
 if [ -z "${def_path:-}" ]; then
 	init_timeout="-1"
@@ -411,7 +413,7 @@ preenable
 
 step "Enabling ${color_term}strata${color_norm}"
 
-notice "Enabling ${color_strat}bedrock${color_norm}"
+einfo "Enabling ${color_strat}bedrock${color_norm}"
 # Cannot brl-enable bedrock or init stratum, and cannot brl-repair disabled
 # strata.  Thus, manually set up minimum required to mark strata as enabled
 # then run brl-repair on bedrock and init strata.
@@ -422,7 +424,7 @@ touch "/bedrock/strata/bedrock/bedrock/run/enabled_strata/${init_stratum}"
 
 /bedrock/libexec/brl-repair "bedrock"
 
-notice "Enabling ${color_strat}${init_stratum}${color_norm}"
+einfo "Enabling ${color_strat}${init_stratum}${color_norm}"
 /bedrock/libexec/brl-repair "${init_stratum}"
 
 for stratum in $(list_strata); do
@@ -431,7 +433,7 @@ for stratum in $(list_strata); do
 		! has_attr "/bedrock/strata/${stratum}" "show_boot"; then
 		continue
 	fi
-	notice "Enabling ${color_strat}${stratum}${color_norm}"
+	einfo "Enabling ${color_strat}${stratum}${color_norm}"
 	/bedrock/libexec/brl-enable "${stratum}"
 done
 
diff --git a/src/slash-bedrock/bin/brl b/src/slash-bedrock/bin/brl
--- a/src/slash-bedrock/bin/brl
+++ b/src/slash-bedrock/bin/brl
@@ -1,20 +1,17 @@
-#!/bedrock/libexec/busybox sh
-#
-# brl
-#
-#      This program is free software; you can redistribute it and/or
-#      modify it under the terms of the GNU General Public License
-#      version 2 as published by the Free Software Foundation.
-#
-# Copyright (c) 2012-2018 Daniel Thau <danthau@bedrocklinux.org>
-#
-# This program manages and provides information about a Bedrock Linux install
-# and its subsystems.
+#!/bin/sh
+# shellcheck shell=sh
+# Copyright 2019 Jacob Hrbek <kreyren@rixotstudio.cz>
+# Distributed under the terms of the GNU General Public License v3 (https://www.gnu.org/licenses/gpl-3.0.en.html) or later
+# Based in part upon 'brl-fetch' from Bedrock Linux (https://github.com/bedrocklinux/bedrocklinux-userland/blob/master/src/slash-bedrock/bin/brl), which is:
+# 		Copyright 2016-2019 Daniel Thau <danthau@bedrocklinux.org> as GPLv2
 
-. /bedrock/share/common-code
+# shellcheck source=src/slash-bedrock/lib/shell/common-code.sh
+. /bedrock/lib/shell/common-code.sh
+
+filename="${0##*/}"
 
 print_help() {
-	printf "Usage: ${color_cmd}brl ${color_sub}<command> [arguments]${color_norm}
+	printf '%s\n' "Usage: ${color_cmd}brl ${color_sub}<command> [arguments]${color_norm}
 
 ${color_bedrock}Bedrock Linux${color_norm} system management and introspection.
 
@@ -55,20 +52,19 @@ See ${color_cmd}\`brl ${color_sub}<command>${color_cmd} --help\`${color_norm} fo
 "
 }
 
-case "${1:-}" in
-"-h" | "--help" | "help" | "")
-	print_help
-	exit_success
-	;;
-"strat" | "list" | "which" | "fetch" | "remove" | "rename" | "copy" | "status" | "enable" | "disable" | "repair" | "hide" | "show" | "alias" | "deref" | "apply" | "update" | "version" | "report" | "tutorial")
-	backend="/bedrock/libexec/brl-${1}"
-	shift
-	exec "${backend}" "${@}"
-	abort "Unable to execute \`${backend}\`"
-	;;
-*)
-	abort "Unrecognized brl subcommand.  See \`${0} --help\`"
-	;;
-esac
+args="$1"
 
-exit_success
+while [ $# -gt 1 ]; do case "${args:-}" in
+	"strat" | "list" | "which" | "fetch" | "remove" | "rename" | "copy" | "status" | "enable" | "disable" | "repair" | "hide" | "show" | "alias" | "deref" | "apply" | "update" | "version" | "report" | "tutorial")
+		backend="/bedrock/libexec/$filename-$args"
+		shift 1
+		exec "/bedrock/libexec/$filename-$args" "$backend" "$@" || die 1 "$filename has been unable to process $*"
+	;;
+	"-h" | "--help" | "help" | "")
+		print_help
+		die 0
+	;;
+	*)
+		printf_help
+		die 2 "Unknown argument has been parsed in $filename - $args"
+esac; done
